# Configuration for agglomerative matching workflow

# Global parameters
index_size: 10000

# Seed ranges for different configurations
seeds:
  no_weights: 
    start: 1
    end: 499
  with_weights:
    start: 500
    end: 999

# SLURM resource requirements
resources:
  import:
    time: "00:30:00"
    mem: "4G"
    cpus: 1
  construct_superlands:
    time: "01:00:00" 
    mem: "8G"
    cpus: 1
  matching:
    time: "01:00:00"
    mem: "8G" 
    cpus: 1
  summarize:
    time: "00:15:00"
    mem: "2G"
    cpus: 1
  visualize:
    time: "00:15:00"
    mem: "2G"
    cpus: 1

# Input data files (land type combinations)
land_types:
  # Files that require superlands construction (private land comparisons)
  private_comparisons:
    - "com_as_priv"
    - "com_iq_priv" 
    - "com_pa_priv"
    - "com_pub_priv"
    - "com_i_priv"
    - "com_q_priv"
  
  # Files that can be matched directly (non-private comparisons)
  direct_comparisons:
    - "com_as_pa"
    - "com_as_pub"
    - "com_iq_pa"
    - "com_iq_pub"
    - "com_pub_pa"