cluster: "sbatch --parsable --job-name={rule}_{wildcards} --output=logs/slurm_%j.out --time={resources.time} --mem={resources.mem} --cpus-per-task={resources.cpus}"
cluster-status: "python profiles/slurm/slurm_status.py"
cluster-cancel: "scancel"
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: False